### PR TITLE
Added net45 target framework.

### PR DESCRIPTION
**Pull request by alexandre-lecoq**

### CODE REVIEW

**Comment by nickbabcock** [comment]
Looks good. Thanks for the work you put into https://github.com/nickbabcock/Farmhash.Sharp/pull/22

Does documentation exist anywhere that explains how / why a .net 4.8 environment won't support netstandard 2.0? Maybe there are other open source projects that ran into the same issue and we can reference those. I just want to avoid the possibility of, sometime far in the future, accidentally removing the net48 target as all documentation found so far points to a net48 environment fully supporting netstandard 2.0 dependency free.

**Comment by alexandre-lecoq** [comment]
In [Getting Started with CLR Integration](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration/database-objects/getting-started-with-clr-integration?view=sql-server-ver15), I found this text :
> Loading CLR database objects on Linux is supported, but they must be built with the .NET Framework (SQL Server CLR integration does not support .NET Core). Also, CLR assemblies with the EXTERNAL_ACCESS or UNSAFE permission set are not supported on Linux.

It's about Linux, but the comment about SQL Server CLR integration seems generic (at least, in regard to my experience). It doesn't state anything about netstandard but it states explicitly you must target the .NET Framework (which I understand as targeting 4.x).

**Comment by nickbabcock** [comment]
Excellent! Did you try a lower bound than net48? Like net45, net451, etc? Ideally we want the lowest bounds that still works.

**Comment by alexandre-lecoq** [comment]
net45 works in SQL Server 2017.

**Comment by nickbabcock** [comment]
Cool it all looks good. I'll merge this after mulling it over for a bit.

**Comment by nickbabcock** [comment]
Thank you again for all your patience 🎉

**Comment by alexandre-lecoq** [comment]
Thanks a lot.

**Pull request merged**
